### ISSUE TITLE
Nested table issue

### ISSUE THREAD

**Issue by zaibon** [jumpscale7/python-consistent-toml#19]
What I would like to create is

```
[[listen]]
Addr = ":8389"

   [[listen.tls]]
   cert = "cert"
```

I tried two different manner, but the result is not the one expected.  What the proper way to create nested table ?

```
In [7]: cfg = contoml.new()

In [8]: cfg.array('listen').append({'Addr':':8389'})

In [9]: cfg.array('listen.tls').append({'cert':'cert'})

In [10]: print cfg.dumps()
[[listen]]
Addr = ":8389"

[["listen.tls"]]
cert = "cert"
```

```
In [11]: cfg = contoml.new()

In [12]: cfg.array('listen').append({'Addr':':8389'})

In [13]: cfg.array('listen').append({'tls':{'cert':'cert'}})

In [14]: print cfg.dumps()
[[listen]]
Addr = ":8389"

[[listen]]
tls = {cert = "cert"}
```

**Comment by amrhassan** [comment]
`cfg.array('listen').append({'tls':{'cert':'cert'}})` is the correct way for constructing this.

The produced TOML is equivalent to the one desired initially but with an inline table instead. Unfortunately contoml doesn't currently support fine-grained control over the final format of the produced TOML tables. You might get flat tables sometimes and inline tables other times.

**Comment by robvanmieghem** [comment]
so does this support

**Comment by zaibon** [comment]
```
toml = '/opt/jumpscale7/apps/agentcontroller2/agentcontroller2.toml'
cfg = contoml.load(toml)
cfg.array('listen')[0]['tls'] = {'cert': cert, 'key': key}
cfg.array('listen')[0]['clientCA'] = {'cert': ca}
```

```
[main]
redis_host =  "127.0.0.1"
redis_password = ""

#Default http
[[listen]]
  Address = ":8966"
  tls = {cert = """
/opt/code/github/jumpscale/ays2/services/agentcontroller2!main/tls/cert.pem\
""", key = """
/opt/code/github/jumpscale/ays2/services/agentcontroller2!main/tls/key.pem\
"""}
  clientCA = {cert = """
/opt/code/github/jumpscale/ays2/services/agentcontroller2!main/tls/ca.pem\
"""}

#Example for https with multiple virtual hosts and clientcertificates
#[[listen]]
#  Address = ":8443"
#  [[listen.tls]]
#    cert = "/path/to/domain1_certificate.cert"
#    key = "/path/to/domain1_keyfile.key"
#  [[listen.tls]]
#    cert = "/path/to/domain2_certificate.cert"
#    key = "/path/to/domain2_keyfile.key"
#  [[listen.clientCA]]
#    cert = "/path/to/CAcert1.cert"
#  [[listen.clientCA]]
#    cert = "/path/to/CAcert2.cert"

[influxdb]
host = "127.0.0.1:8086"
db   = "main"
user = "root"
password = "root"

[handlers]
binary = "python2.7"
cwd = "./handlers"
    [handlers.env]
    PYTHONPATH = "/opt/jumpscale7/lib"
    HOME = "/root"
    SYNCTHING_URL = "http://localhost:18384/"
    #SYNCTHING_API_KEY = ""
    REDIS_ADDRESS = "127.0.0.1"
    REDIS_PORT = ""
    REDIS_PASSWORD = ""
    #REDIS_PASSWORD = ""

##### The following 2 sections are supportive for syncthing operation
##### Please don't remove or edit unless you know what you are doing
##### This will get replace once we implement local transport for hubbble.
[syncthing]
port=9066

[[listen]]
address="127.0.0.1:9066"
##### END SECTION.
root@lubeg:/opt/jum
```

```
cd /opt/jumpscale7/apps/agentcontroller2/; ./agentcontroller2 -c agentcontroller2.toml
root@lubeg:/opt/code/github/jumpscale/ays2# cd /opt/jumpscale7/apps/agentcontroller2/; ./agentcontroller2 -c agentcontroller2.toml
Error loading configuration file: toml: unmarshal: line 8: `main.HTTPBinding.TLS' must be struct or map, but slice given
panic: Error loading configuration file: toml: unmarshal: line 8: `main.HTTPBinding.TLS' must be struct or map, but slice given
```

Multiple problem here : 
- why ``` {cert = """
/opt/code/github/jumpscale/ays2/services/agentcontroller2!main/tls/cert.pem\
""", ``` is on multi-line ?
- this doesn't produce valid toml for the golang parser, which is the official implementation reference. 

Need to be fix ASAP, this is blocking us to start using agent2 and agentcontroller2

**Comment by amrhassan** [comment]
Spanning long strings over multiple lines is part of the prettification logic. I'll try to make that not happen in inline tables (#21).

Which Go parser are you using? Because I think inline tables are new in TOML v0.4 and only this one is listed as v0.4-compatible: https://github.com/naoina/toml

**Comment by zaibon** [comment]
I think we use this lib https://github.com/BurntSushi/toml
Maybe testing with https://github.com/naoina/toml would worth a shot.

**Comment by zaibon** [comment]
My bad. actually the toml lib used is already https://github.com/naoina/toml.
see https://github.com/Jumpscale/agentcontroller2/blob/master/settings.go#L7

**Comment by amrhassan** [comment]
It's weird that it can't parse inline tables.

Anyway I'm trying to make contoml not create new inline tables (see #23).

**Comment by robvanmieghem** [comment]
Yes, it can parse inline tables.
And please don't close this one all the time, we need to be able to construct inline tables like the example given above.

**Comment by amrhassan** [comment]
I don't understand. If it can read inline tables, then why is it complaining about line 8? I can see nothing wrong with it.

**Comment by amrhassan** [comment]
contoml has been stripped back down to its original purpose - which is to update pre-written TOML files without messing up their formatting. Support for constructing new sections/entries is currently dropped. Please use another Python module for your TOML serialization needs (like [pytoml](https://github.com/avakar/pytoml)).

The TOML formatting features have been moved to the project [prettytoml](https://github.com/Jumpscale/python-pretty-toml). Feel free to report any issues about the latter project on its issue tracker.

**Comment by robvanmieghem** [comment]
WTF? Who decided this?

**Comment by amrhassan** [comment]
@grimpy did. contoml needed some major internal rewriting to make TOML construction from scratch correct (since it was not in the initial requirements), and it was decided that the extra work and complexity isn't worth it when all that is needed is a TOML formatter.
